### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by 456chenxigang** [HelloSoul/android-webrtc-aec#1]
`
Error:(687) Android NDK: Module webrtc_android depends on undefined modules: cutils dl protobuf-cpp-lite`
`
Error:(700) *** Android NDK: Aborting (set APP_ALLOW_MISSING_DEPS=true to allow missing dependencies)    .  Stop.
`
`
Error:Execution failed for task ':libwebrtcaec:ndkBuild'.
> Process 'command '/Users/cxg/Library/Android/sdk/ndk-bundle/ndk-build'' finished with non-zero exit value 2``

**Comment by HelloSoul** [comment]
刚刚我从github上下载下来一个，测试了一下，编译没有问题。我这边的ndk版本是r13b。

**Comment by HelloSoul** [comment]
从你的打印来看是链接库没找到，一会我重新提交一下，你再试试。
